### ISSUE TITLE
Just a Little Query

### ISSUE THREAD

**Issue by Sindhani** [Chahtsham96/logfile#1]
What will happen if let say I have more than 5 types of user in my system. where will you make the change??

**Comment by Chahtsham96** [comment]
hm is ki type baraha dn ga like user model maOs ma hm first 1 super admin 2  admin3 Manager4 client 5 usersSent from my Samsung Galaxy smartphone.
-------- Original message --------From: sindhani <notifications@github.com> Date: 10/15/20  11:04 AM  (GMT+05:00) To: Chahtsham96/logfile <logfile@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Chahtsham96/logfile] Just a Little Query (#1) 
What will happen if let say I have more than 5 types of user in my system. where will you make the change??

**Comment by Chahtsham96** [comment]
?
